(* Proc macro concepts in OCaml via ppx *)

(* ppx_deriving example — what a custom derive would generate *)
(* Without ppx, we write the boilerplate manually *)

type describable = {
  type_name: string;
  field_names: string list;
  field_values: string list;
}

(* Simulate what #[derive(Describe)] would generate *)
let make_describable tn fns fvs = { type_name=tn; field_names=fns; field_values=fvs }

let describe d =
  Printf.printf "%s { " d.type_name;
  List.iter2 (fun name value ->
    Printf.printf "%s: %s, " name value
  ) d.field_names d.field_values;
  Printf.printf "}\n"

type person = { name: string; age: int }

(* Generated by hypothetical #[derive(Describe)] *)
let describe_person p =
  describe (make_describable "Person"
    ["name"; "age"]
    [p.name; string_of_int p.age])

let () =
  describe_person {name = "Alice"; age = 30}
