(* Custom derive concept in OCaml *)

(* ppx_deriving.show generates to_string/pp functions *)
(* We simulate what it generates manually *)

type color = Red | Green | Blue | Custom of int * int * int

(* Generated by [@@deriving show] *)
let pp_color fmt = function
  | Red -> Format.pp_print_string fmt "Red"
  | Green -> Format.pp_print_string fmt "Green"
  | Blue -> Format.pp_print_string fmt "Blue"
  | Custom (r,g,b) -> Format.fprintf fmt "Custom (%d, %d, %d)" r g b

let show_color c =
  let buf = Buffer.create 16 in
  let fmt = Format.formatter_of_buffer buf in
  pp_color fmt c;
  Format.pp_print_flush fmt ();
  Buffer.contents buf

(* Generated by [@@deriving eq] *)
let equal_color a b = match (a, b) with
  | (Red, Red) | (Green, Green) | (Blue, Blue) -> true
  | (Custom (r1,g1,b1), Custom (r2,g2,b2)) -> r1=r2 && g1=g2 && b1=b2
  | _ -> false

let () =
  let colors = [Red; Green; Blue; Custom (128, 64, 255)] in
  List.iter (fun c -> Printf.printf "%s\n" (show_color c)) colors;
  Printf.printf "Red = Red: %b\n" (equal_color Red Red);
  Printf.printf "Red = Blue: %b\n" (equal_color Red Blue)
