// Repetition patterns in macros ($(...),*)

// sum of any number of values
macro_rules! sum {
    () => { 0 };
    ($first:expr $(, $rest:expr)*) => {
        $first $(+ $rest)*
    };
}

// product
macro_rules! product {
    () => { 1 };
    ($first:expr $(, $rest:expr)*) => {
        $first $(* $rest)*
    };
}

// create a struct with named fields from macro
macro_rules! make_struct {
    ($name:ident { $($field:ident : $ty:ty),* $(,)? }) => {
        #[derive(Debug, Default)]
        struct $name {
            $($field: $ty,)*
        }
    };
}

// implement multiple From impls at once
macro_rules! impl_from_int {
    ($target:ty : $($source:ty),*) => {
        $(
            impl From<$source> for $target {
                fn from(x: $source) -> $target {
                    x as $target
                }
            }
        )*
    };
}

impl_from_int!(f64 : i8, i16, i32, u8, u16, u32);

// print table with repetition
macro_rules! print_table {
    ($($key:expr => $val:expr),* $(,)?) => {
        {
            $(println!("  {:20} = {}", $key, $val);)*
        }
    };
}

make_struct!(Config {
    port: u16,
    timeout: u32,
    debug: bool,
});

fn main() {
    println!("sum(1,2,3,4,5) = {}", sum!(1, 2, 3, 4, 5));
    println!("sum() = {}", sum!());
    println!("product(1,2,3,4) = {}", product!(1, 2, 3, 4));

    let c = Config { port: 8080, timeout: 30, debug: true };
    println!("Config: {:?}", c);

    // From impls generated by repetition
    let x: f64 = 42u32.into();
    println!("u32 -> f64: {}", x);

    print_table!(
        "host" => "localhost",
        "port" => 8080,
        "debug" => true,
    );
}

#[cfg(test)]
mod tests {
    #[test]
    fn test_sum_macro() {
        assert_eq!(sum!(1, 2, 3), 6);
        assert_eq!(sum!(), 0);
        assert_eq!(sum!(10), 10);
    }

    #[test]
    fn test_product_macro() {
        assert_eq!(product!(2, 3, 4), 24);
        assert_eq!(product!(5), 5);
    }
}
